# protocol/constants.py

#TCP Operations
REGISTER = "REGISTER"
REGISTERED = "REGISTERED"
REGISTER_DENIED = "REGISTER-DENIED"
REFER = "REFER"

GET_USER_BY_IP = "GET-USER-BY-IP"
USER_INFO = "USER-INFO"

LIST_USERS = "LIST-USERS"
USERS_LIST = "USERS-LIST"

UPDATE = "UPDATE"
UPDATE_CONFIRMED = "UPDATE-CONFIRMED"
UPDATE_DENIED = "UPDATE-DENIED"

SUBJECTS = "SUBJECTS"
SUBJECTS_UPDATED = "SUBJECTS-UPDATED"
SUBJECTS_REJECTED = "SUBJECTS-REJECTED"

DE_REGISTER = "DE-REGISTER"

#UDP Operations
PUBLISH = "PUBLISH"
PUBLISH_CONFIRMED = "PUBLISH-CONFIRMED"
PUBLISH_DENIED = "PUBLISH-DENIED"
MESSAGE = "MESSAGE"
FORWARD = "FORWARD"
FORWARD_ACK = "FORWARD-ACK"
PUBLISH_COMMENT = "PUBLISH-COMMENT"
COMMENT = "COMMENT"

# Cross-server name uniqueness
NAME_CHECK = "NAME-CHECK"
NAME_CHECK_REPLY = "NAME-CHECK-REPLY"

#Valid Subjects
VALID_SUBJECTS = [
    "Sports",
    "Technology",
    "Politics",
    "Entertainment",
    "Science",
    "Business",
    "Health",
]
