# protocol/constants.py

REGISTER = "REGISTER"
REGISTERED = "REGISTERED"
REGISTER_DENIED = "REGISTER-DENIED"
REFER = "REFER"

UPDATE = "UPDATE"
UPDATE_CONFIRMED = "UPDATE-CONFIRMED"
UPDATE_DENIED = "UPDATE-DENIED"

SUBJECTS = "SUBJECTS"
SUBJECTS_UPDATED = "SUBJECTS-UPDATED"
SUBJECTS_REJECTED = "SUBJECTS-REJECTED"

DE_REGISTER = "DE-REGISTER"

